apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-hello-world-deployment
  labels:
    app: spring-boot-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-hello-world
  template:
    metadata:
      labels:
        app: spring-boot-hello-world
    spec:
      containers:
        - name: spring-boot-hello-world
          image: kvpratapr/spring-boot-hello-world
          ports:
            - containerPort: 8080
          lifecycle:
            postStart:
              exec:
                command: [ "touch", "/tmp/health"]
          livenessProbe:
            exec:
              command:
              - cat
              - /tmp/health
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 4
          readinessProbe:
            exec:
              command:
                - echo
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 4
#          volumeMounts:
#            - name: tmp
#              mountPath: /tmp/healthy
#      volumes:
#        # For /tmp to be writable
#        - name: tmp
#          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-hello-world-service
spec:
  type: NodePort
  selector:
    app: spring-boot-hello-world
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100